complete -c "catkin_make" -f
complete -c "catkin_make" -s "h" -l "help" -n "not __fish_seen_subcommand_from -h --help" -d "show help message and exit"
complete -c "catkin_make" -s "C" -l "directory" -F -n "not __fish_seen_subcommand_from -C --directory" -d "The base path of the workspace (default '.')"
complete -c "catkin_make" -l "source" -F -n "not __fish_seen_subcommand_from --source" -d "The path to the source space (default 'workspace_base/src')"
complete -c "catkin_make" -l "build" -F -n "not __fish_seen_subcommand_from --build" -d "The path to the build space (default 'workspace_base/build')"
complete -c "catkin_make" -l "use-ninja" -n "not __fish_seen_subcommand_from --use-ninja --use-nmake --use-gmake" -d "Use 'ninja' instead of 'make'"
complete -c "catkin_make" -l "use-nmake" -n "not __fish_seen_subcommand_from --use-ninja --use-nmake --use-gmake" -d "Use 'nmake' instead of 'make'"
complete -c "catkin_make" -l "use-gmake" -n "not __fish_seen_subcommand_from --use-ninja --use-nmake --use-gmake" -d "Use 'gmake' instead of 'make'"
complete -c "catkin_make" -l "force-cmake" -n "not __fish_seen_subcommand_from --force-cmake" -d "Invoke 'cmake' even if it has been executed before"
complete -c "catkin_make" -l "no-color" -n "not __fish_seen_subcommand_from --no-color" -d "Disables colored output (only for catkin_make and CMake)"
complete -c "catkin_make" -l "pkg" -a "(__fish_print_ros_packages)" -d "Invoke 'make' on specific packages only"
complete -c "catkin_make" -l "only-pkg-with-deps" -a "(__fish_print_ros_packages)" -d "Whitelist only the specified packages and their dependencies."
complete -c "catkin_make" -l "cmake-args" -d "Arbitrary arguments which are passed to CMake. It must be passed after other arguments since it collects all following options."
complete -c "catkin_make" -l "make-args" -d "Arbitrary arguments which are passes to make. It must be passed after other arguments since it collects all following options. This is only necessary in combination with --cmake-args since else all unknown arguments are passed to make anyway."
complete -c "catkin_make" -l "override-build-tool-check" -n "not __fish_seen_subcommand_from --override-build-tool-check" -d "use to override failure due to using different build tools on the same workspace."